### ISSUE TITLE
knn import issue from classifier

### ISSUE THREAD

**Issue by nghuiqin** [baby03201/C231n#1]
ModuleNotFoundError: No module named 'past'
![screen shot 2018-02-07 at 5 48 19 pm](https://user-images.githubusercontent.com/923188/35909610-1ea75790-0c2f-11e8-8a84-93450feaf734.png)

**Comment by baby03201** [comment]
To solve this issue, run the command below:
`pip install future`

**Comment by nghuiqin** [comment]
To solve this issue, run the command below:
`pip install future`
